### ISSUE TITLE
Possible sync out of order

### ISSUE THREAD

**Issue by sgorman** [carsonreinke/git-scp#1]
When deploying from origin, adds are done first, then removals.

If a file is removed then re-added later between two commits it should not be removed.

**Comment by carsonreinke** [comment]
Won't `git log` report this correctly?

**Comment by sgorman** [comment]
Yes however the script splits the responses. Into different action queues
then fires them one after another.

**Comment by carsonreinke** [comment]
Strange, I see what you are saying now.  Here is example were I delete and then re-add a file:

```
workstation-1:testing carsonreinke$ git log HEAD~2..HEAD --name-status --pretty="format:" --abbrev-commit
A       test.txt

D       test.txt
```

**Comment by carsonreinke** [comment]
It gets even stranger the more commits you have:

```
workstation-1:testing carsonreinke$ git log HEAD~4..HEAD --name-status --pretty="format:" --abbrev-commit
A       test.txt

D       test.txt

A       test.txt

D       test.txt
```

**Comment by carsonreinke** [comment]
Maybe switch to use `git diff` instead and extracting AMD from there.

**Comment by sgorman** [comment]
#3 will resolve this issue without having to change the file matching by using git diff. I propose a separate branch for reworking the system to be smarter.

**Comment by carsonreinke** [comment]
Sounds good pimp
